packet: Fix false positive compilation error
This fixes the compilation error -

net/packet/af_packet.o: In function `check_copy_size':
include/linux/thread_info.h:136: undefined reference to `__bad_copy_to'

CRs-Fixed: 2395803
Change-Id: I33a7ec2413da0e4febc3f119c1f70ffa6c950158
Signed-off-by: Subash Abhinov Kasiviswanathan <subashab@codeaurora.org>
(cherry picked from commit 866e6553b64b055239fdeeef38a459b42a8c0935)
Signed-off-by: Planet-X <planetx.dev@gmail.com>